-- Courses Table
CREATE TABLE IF NOT EXISTS `courses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text,
  `short_description` varchar(500),
  `category_id` int(11) NOT NULL,
  `subcategory_id` int(11) NOT NULL,
  `course_type` enum('e-learning', 'classroom', 'blended', 'assessment') NOT NULL DEFAULT 'e-learning',
  `difficulty_level` enum('beginner', 'intermediate', 'advanced', 'expert') NOT NULL DEFAULT 'beginner',
  `duration_hours` decimal(5,2) DEFAULT NULL COMMENT 'Estimated duration in hours',
  `duration_minutes` int(11) DEFAULT NULL COMMENT 'Additional minutes',
  `max_attempts` int(11) DEFAULT 1 COMMENT 'Maximum attempts allowed',
  `passing_score` decimal(5,2) DEFAULT 70.00 COMMENT 'Minimum score to pass (percentage)',
  `is_self_paced` tinyint(1) NOT NULL DEFAULT '1',
  `is_featured` tinyint(1) NOT NULL DEFAULT '0',
  `is_published` tinyint(1) NOT NULL DEFAULT '0',
  `thumbnail_image` varchar(255) DEFAULT NULL,
  `banner_image` varchar(255) DEFAULT NULL,
  `tags` text COMMENT 'JSON array of tags',
  `learning_objectives` text COMMENT 'JSON array of learning objectives',
  `prerequisites` text COMMENT 'JSON array of prerequisite course IDs',
  `target_audience` text COMMENT 'Description of target audience',
  `certificate_template` varchar(255) DEFAULT NULL COMMENT 'Certificate template file path',
  `completion_criteria` text COMMENT 'JSON object defining completion criteria',
  `created_by` int(11) NOT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_client_id` (`client_id`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_subcategory_id` (`subcategory_id`),
  KEY `idx_course_type` (`course_type`),
  KEY `idx_difficulty_level` (`difficulty_level`),
  KEY `idx_is_published` (`is_published`),
  KEY `idx_is_featured` (`is_featured`),
  KEY `idx_is_deleted` (`is_deleted`),
  KEY `idx_created_by` (`created_by`),
  KEY `idx_created_at` (`created_at`),
  FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`category_id`) REFERENCES `course_categories`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`subcategory_id`) REFERENCES `course_subcategories`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`created_by`) REFERENCES `user_profiles`(`id`),
  FOREIGN KEY (`updated_by`) REFERENCES `user_profiles`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Courses table';

-- Course Modules Table
CREATE TABLE IF NOT EXISTS `course_modules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `course_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `is_required` tinyint(1) NOT NULL DEFAULT '1',
  `estimated_duration` int(11) DEFAULT NULL COMMENT 'Duration in minutes',
  `learning_objectives` text COMMENT 'JSON array of module-specific learning objectives',
  `created_by` int(11) NOT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_sort_order` (`sort_order`),
  KEY `idx_is_deleted` (`is_deleted`),
  KEY `idx_created_by` (`created_by`),
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`created_by`) REFERENCES `user_profiles`(`id`),
  FOREIGN KEY (`updated_by`) REFERENCES `user_profiles`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Course modules/sections table';

-- Course Module Content Table
CREATE TABLE IF NOT EXISTS `course_module_content` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `module_id` int(11) NOT NULL,
  `content_type` enum('scorm', 'non_scorm', 'assessment', 'audio', 'video', 'document', 'image', 'external', 'survey', 'feedback', 'interactive', 'assignment') NOT NULL,
  `content_id` int(11) NOT NULL COMMENT 'ID from respective content table',
  `title` varchar(255) NOT NULL,
  `description` text,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `is_required` tinyint(1) NOT NULL DEFAULT '1',
  `estimated_duration` int(11) DEFAULT NULL COMMENT 'Duration in minutes',
  `completion_criteria` text COMMENT 'JSON object defining completion criteria',
  `created_by` int(11) NOT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_module_id` (`module_id`),
  KEY `idx_content_type` (`content_type`),
  KEY `idx_content_id` (`content_id`),
  KEY `idx_sort_order` (`sort_order`),
  KEY `idx_is_deleted` (`is_deleted`),
  KEY `idx_created_by` (`created_by`),
  FOREIGN KEY (`module_id`) REFERENCES `course_modules`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`created_by`) REFERENCES `user_profiles`(`id`),
  FOREIGN KEY (`updated_by`) REFERENCES `user_profiles`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Course module content items table';

-- Course Prerequisites Table
CREATE TABLE IF NOT EXISTS `course_prerequisites` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `course_id` int(11) NOT NULL,
  `prerequisite_course_id` int(11) NOT NULL,
  `prerequisite_type` enum('required', 'recommended') NOT NULL DEFAULT 'required',
  `minimum_score` decimal(5,2) DEFAULT NULL COMMENT 'Minimum score required in prerequisite course',
  `created_by` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_course_prerequisite` (`course_id`, `prerequisite_course_id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_prerequisite_course_id` (`prerequisite_course_id`),
  KEY `idx_prerequisite_type` (`prerequisite_type`),
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`prerequisite_course_id`) REFERENCES `courses`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`created_by`) REFERENCES `user_profiles`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Course prerequisites table';

-- Course Assessments Table
CREATE TABLE IF NOT EXISTS `course_assessments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `course_id` int(11) NOT NULL,
  `assessment_id` int(11) NOT NULL COMMENT 'ID from assessment_package table',
  `assessment_type` enum('pre_course', 'post_course', 'module_assessment') NOT NULL DEFAULT 'post_course',
  `module_id` int(11) DEFAULT NULL COMMENT 'NULL for pre/post course assessments',
  `title` varchar(255) NOT NULL,
  `description` text,
  `is_required` tinyint(1) NOT NULL DEFAULT '1',
  `passing_score` decimal(5,2) DEFAULT 70.00 COMMENT 'Minimum score to pass (percentage)',
  `max_attempts` int(11) DEFAULT 1,
  `time_limit` int(11) DEFAULT NULL COMMENT 'Time limit in minutes',
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_by` int(11) NOT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_assessment_id` (`assessment_id`),
  KEY `idx_assessment_type` (`assessment_type`),
  KEY `idx_module_id` (`module_id`),
  KEY `idx_is_deleted` (`is_deleted`),
  KEY `idx_created_by` (`created_by`),
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`assessment_id`) REFERENCES `assessment_package`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`module_id`) REFERENCES `course_modules`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`created_by`) REFERENCES `user_profiles`(`id`),
  FOREIGN KEY (`updated_by`) REFERENCES `user_profiles`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Course assessments table';

-- Course Feedback Table
CREATE TABLE IF NOT EXISTS `course_feedback` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `course_id` int(11) NOT NULL,
  `feedback_id` int(11) NOT NULL COMMENT 'ID from feedback_package table',
  `feedback_type` enum('pre_course', 'post_course', 'module_feedback') NOT NULL DEFAULT 'post_course',
  `module_id` int(11) DEFAULT NULL COMMENT 'NULL for pre/post course feedback',
  `title` varchar(255) NOT NULL,
  `description` text,
  `is_required` tinyint(1) NOT NULL DEFAULT '0',
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_by` int(11) NOT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_feedback_id` (`feedback_id`),
  KEY `idx_feedback_type` (`feedback_type`),
  KEY `idx_module_id` (`module_id`),
  KEY `idx_is_deleted` (`is_deleted`),
  KEY `idx_created_by` (`created_by`),
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`feedback_id`) REFERENCES `feedback_package`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`module_id`) REFERENCES `course_modules`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`created_by`) REFERENCES `user_profiles`(`id`),
  FOREIGN KEY (`updated_by`) REFERENCES `user_profiles`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Course feedback table';

-- Course Surveys Table
CREATE TABLE IF NOT EXISTS `course_surveys` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `course_id` int(11) NOT NULL,
  `survey_id` int(11) NOT NULL COMMENT 'ID from survey_package table',
  `survey_type` enum('pre_course', 'post_course', 'module_survey') NOT NULL DEFAULT 'post_course',
  `module_id` int(11) DEFAULT NULL COMMENT 'NULL for pre/post course surveys',
  `title` varchar(255) NOT NULL,
  `description` text,
  `is_required` tinyint(1) NOT NULL DEFAULT '0',
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_by` int(11) NOT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_survey_id` (`survey_id`),
  KEY `idx_survey_type` (`survey_type`),
  KEY `idx_module_id` (`module_id`),
  KEY `idx_is_deleted` (`is_deleted`),
  KEY `idx_created_by` (`created_by`),
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`survey_id`) REFERENCES `survey_package`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`module_id`) REFERENCES `course_modules`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`created_by`) REFERENCES `user_profiles`(`id`),
  FOREIGN KEY (`updated_by`) REFERENCES `user_profiles`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Course surveys table';

-- Course Settings Table
CREATE TABLE IF NOT EXISTS `course_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `course_id` int(11) NOT NULL,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text,
  `setting_type` enum('string', 'integer', 'boolean', 'json') NOT NULL DEFAULT 'string',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_course_setting` (`course_id`, `setting_key`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_setting_key` (`setting_key`),
  FOREIGN KEY (`course_id`) REFERENCES `courses`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Course settings table'; 